language: php

php:
  - 5.4
  - 5.5
  - hhvm

notifications:
  email: false
  slack:
    secure: U7Uon5zoExEX1StIOyQQJ9AVhnuxPfnWe2k55RPVAZqUMLZAqLT25yRzzhGv5FHlckd3ZX+JoZ4qWmcVnsVduMW2Ogij75YRq7sT+xTFkIJ45E7uWnnqnUuhY3HcZGlkNNlUwN3+RW0l8oskLHQltGLLZiG0r0HEuZSLl2OS9OA=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
